{% set name = "Yapsy" %}
{% set version = "1.12.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "f08cb229a96f14cc0b1d4b68cb7c111d1020ab8c3989b426d3aa39b82d6a3e3c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - yapsy

about:
  home: http://yapsy.sourceforge.net
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Yet another plugin system
  description: "Yapsy is a small library implementing the core mechanisms needed to build a plugin system."
  doc_url: 'http://yapsy.sourceforge.net'
  dev_url: 'https://github.com/tibonihoo/yapsy'

extra:
  recipe-maintainers:
    - ganeshhubale
