travis:
  secure:
    BINSTAR_TOKEN: IZXO3f+g7SPpqTMNHgcxqbchWz1nx7EFCA/7y1s6uQPm5xMQJs3o9QYql5ekv+lbyyn5JTwW3fJH7fUVPwNgB2OUXrAr0/Nj4SgluWpMXXHHTXpjKCqM0B1vFPLH3ejPDlTq9aX1yN4qqbKLIcNwDTKcMvauk4enxFu8brdRkldiqB/jasuO9NxNG6O2atHsbnByihzMbeHAnwHVgagz7J4riLQrLuX4wHSiTVC7jyLW6hC4nXGlqXkDn+oeWdf9a9Q18ZWLxEI7oElVL0OAVdc7hNbM9pFVD2UhfgQ6QMc+EwunywHs7dc+Y+bqznmlQlIguja1uUjcBDDtOt/fyc8slna7l5u2fSd/qaPms0IYH+fs/J+Qr2RpN9gbf309BSccHMzwEZPUWL2gtGKiEfd9Bv9MD4qCFSNTGuLdknc7YRjT5mm/JmTFOnpen+2fYzGhJg3n147MksJoyj0LVxWoZyrk0EwIZ1GkPqH9ex7mCxtEjPqY1+QsKjv/iAkoYGlc9P5YtzJfluWK2/8b1qsNlyLKZKJulIzY2LjMslvISS9VGYtYIYtqjv7NghUOhXKkHmvhobeNl9wt0WM7FsevEhYc2ALhq+wPR9zsVAVMh2tIg8pahAO0wnN6iQD68Moaredfh5iTq+X3l67f/B2O7IIqQEXhOhubqXuW5wY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
