travis:
  secure:
    BINSTAR_TOKEN: j3Naf3GQB5LVpjheY2kM2h5o4MNvBAnK2EFn2ILiUyiD+TyhJEE2Y+iqkb28zvK6lx8nBTlrA6NBZU7flWVxThJomtjSeIDpAUdF2VeV45EbQEtiS9Wh3Wx5wxPHGy6cejnKYqSgF0r1Yw8KVjPbkTewG3AfxiQrYUUV28/Qo4KrE9hr131aaCuaNJAwyR3faREJpHadf1jXbWaKJnGdsqE5wh1aXLFgjEkBbtVtmTMNg45y8zUyYHCpK72SFBQqO765E2nD7BaM5610I4ASyMtZDUvgDNRvAxT+W9MRczFg9fMr+JIN3zm1n1lw65ITI9PpBDsA515gQjGAJnJ1aNpLO52COgxNxwy+7tD7o1QQUfBDQ1J1O0nWFgjsEm9oESTtREaGip9njD6PE4bekoKjzkpZxBrkU2YWFuoNqFrBhO3Fghy0wTjfs9l32cQVOLPGQ8yhb9f+i9yQJsC8BkKAFXVk6obA8sdCT8qDECJw4JgiklCySWY7opy4CjEYW6EneFJq980xSgHnJ5GngK3AOxi8KJFV6MSK3eN5ojdGde7yADU2QBwKWvkWUKy1FKUm31Kf8DK/S0MuaaeLWz2ZojcAhuWJShDmXhvK5FS/OlIReFkIcYYwubD6EB0jE+Q+KvSgXEX7Vpkmh5vIcLq7giAUEM/vsV04/rxWfSg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
